export const STRATEGIES = [
  {
    id: 'consistent_compounders',
    name: 'Consistent Compounders',
    emoji: '🏆',
    colorClass: 'emerald',
    borderColor: 'border-emerald-500/40',
    bgColor: 'bg-emerald-500/10',
    textColor: 'text-emerald-400',
    badgeBg: 'bg-emerald-500/20',
    description: 'High-quality businesses with 7+ years of consistent EPS & sales growth',
    criteria: [
      'EPS Growth 3/5/7Y > 20%',
      'Sales Growth 3/5/7Y > 15%',
      'PEG Ratio < 1',
      'Debt/Equity < 1',
      'Market Cap > ₹5,000 Cr',
    ],
    stocks: ['TCS', 'INFY', 'HINDUNILVR', 'PIDILITIND', 'NESTLEIND', 'TITAN', 'ASIANPAINT', 'BAJFINANCE', 'HDFCBANK', 'BRITANNIA', 'DIVISLAB', 'DRREDDY', 'SUNPHARMA'],
  },
  {
    id: 'momentum_kings',
    name: 'Momentum Kings',
    emoji: '🚀',
    colorClass: 'blue',
    borderColor: 'border-blue-500/40',
    bgColor: 'bg-blue-500/10',
    textColor: 'text-blue-400',
    badgeBg: 'bg-blue-500/20',
    description: 'Stocks with strong price momentum, volume surge & bullish technicals',
    criteria: [
      'Price > 200 DMA',
      '52W High Proximity > 80%',
      'RSI between 50–70',
      '3-Month Return > 15%',
      'Volume Above Average',
    ],
    stocks: ['RELIANCE', 'BAJFINANCE', 'TATAMOTORS', 'ZOMATO', 'IRCTC', 'TRENT', 'DMART', 'PERSISTENT', 'COFORGE', 'LTIM', 'KPITTECH', 'BHARTIARTL'],
  },
  {
    id: 'high_roe',
    name: 'High ROE Champions',
    emoji: '💎',
    colorClass: 'purple',
    borderColor: 'border-purple-500/40',
    bgColor: 'bg-purple-500/10',
    textColor: 'text-purple-400',
    badgeBg: 'bg-purple-500/20',
    description: 'Capital-efficient businesses with exceptional return on equity',
    criteria: [
      'ROE > 25%',
      'ROCE > 20%',
      'Debt/Equity < 0.5',
      'Profit Growth > 15%',
      'Market Cap > ₹2,000 Cr',
    ],
    stocks: ['BAJFINANCE', 'TITAN', 'NESTLEIND', 'HINDUNILVR', 'PIDILITIND', 'ASIANPAINT', 'TCS', 'INFY', 'DRREDDY', 'HDFCBANK', 'KOTAK', 'SUNPHARMA'],
  },
  {
    id: 'small_cap_rockets',
    name: 'Small Cap Rockets',
    emoji: '⚡',
    colorClass: 'yellow',
    borderColor: 'border-yellow-500/40',
    bgColor: 'bg-yellow-500/10',
    textColor: 'text-yellow-400',
    badgeBg: 'bg-yellow-500/20',
    description: 'High-growth small caps with strong fundamentals & promoter confidence',
    criteria: [
      'Market Cap ₹500 – ₹5,000 Cr',
      'Revenue Growth > 30%',
      'ROE > 15%',
      'Debt/Equity < 1',
      'Promoter Holding > 50%',
    ],
    stocks: ['DEEPAKNTR', 'PIIND', 'KPITTECH', 'AAVAS', 'CHOLAFIN', 'MUTHOOTFIN', 'CANFINHOME', 'IDFCFIRSTB', 'AUBANK', 'FEDERALBNK', 'TORNTPHARM', 'APLLTD'],
  },
  {
    id: 'fii_darlings',
    name: 'FII Buying Spree',
    emoji: '🌍',
    colorClass: 'cyan',
    borderColor: 'border-cyan-500/40',
    bgColor: 'bg-cyan-500/10',
    textColor: 'text-cyan-400',
    badgeBg: 'bg-cyan-500/20',
    description: 'Stocks where foreign institutions are consistently increasing exposure',
    criteria: [
      'FII Holding Increasing 3Q+',
      'Market Cap > ₹1,000 Cr',
      'Profit Growth > 0%',
      'Institutional Grade Quality',
    ],
    stocks: ['ICICIBANK', 'HDFCBANK', 'INFY', 'TCS', 'RELIANCE', 'BAJFINANCE', 'AXISBANK', 'TECHM', 'LT', 'BHARTIARTL', 'WIPRO', 'HCLTECH'],
  },
  {
    id: 'dividend_aristocrats',
    name: 'Dividend Aristocrats',
    emoji: '💰',
    colorClass: 'orange',
    borderColor: 'border-orange-500/40',
    bgColor: 'bg-orange-500/10',
    textColor: 'text-orange-400',
    badgeBg: 'bg-orange-500/20',
    description: 'High-yield dividend payers with stable cash flows & low debt',
    criteria: [
      'Dividend Yield > 3%',
      'Consistent Dividends 5Y+',
      'Debt/Equity < 1',
      'Market Cap > ₹2,000 Cr',
      'Positive Free Cash Flow',
    ],
    stocks: ['ITC', 'COALINDIA', 'ONGC', 'POWERGRID', 'NTPC', 'BPCL', 'HINDUNILVR', 'TCS', 'INFY', 'SBIN', 'IOC', 'GAIL'],
  },
]
